server:
  port: 8080

spring:
  application:
    name: Profile

  datasource:
    url: jdbc:postgresql://localhost:5432/profile
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver